# Generated by Django 3.1.6 on 2021-02-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
